// src/components/optionPage/AutoComplete.tsx
//./components/Autocomplete.tsx

import React, { memo, useRef, useState } from "react";

type Props = {
	options: string[];
	value: string;
	placeholder: string;
	onChange(val: string): void;
	disabled?: boolean;
};

//we are using dropdown, input and menu component from daisyui
const Autocomplete = (props: Props) => {
	const { options, value, onChange, placeholder, disabled = false } = props;
	const ref = useRef<HTMLDivElement>(null);
	const handleClick = () => {
		const elem = document.activeElement;
		if (elem) {
			(elem as HTMLElement)?.blur();
		}
	};

	const getDisplayOptions = (): string[] => {
		if (value === "") {
			return options;
		}
		return options.filter((option) =>
			option.toLowerCase().includes(value.toLowerCase()),
		);
	};

	return (
		<div
			// use classnames here to easily toggle dropdown open
			className="dropdown w-full"
			ref={ref}
		>
			<input
				type="text"
				className="input input-bordered w-full"
				value={value}
				onChange={(e) => onChange(e.target.value)}
				placeholder={placeholder}
				tabIndex={0}
				disabled={disabled}
			/>
			{/* add this part */}
			<div className="dropdown-content bg-base-200 top-14 max-h-96 overflow-auto flex-col rounded-md w-full">
				<ul
					className="menu menu-compact "
					// use ref to calculate the width of parent
					style={{ width: ref.current?.clientWidth }}
				>
					{getDisplayOptions().map((item, index) => {
						return (
							<li
								key={index}
								tabIndex={index + 1}
								onClick={() => {
									onChange(item);
									handleClick();
								}}
								className="border-b border-b-base-content/10 w-full"
							>
								<button>{item}</button>
							</li>
						);
					})}
				</ul>
				{/* add this part */}
			</div>
		</div>
	);
};

export default memo(Autocomplete);

// src/components/candidate/AutoComplete.vue
<!-- ./components/Autocomplete.vue -->

<template>
	<div class="dropdown w-full" ref="dropdownRef">
		<label class="input input-bordered flex items-center gap-2">
			<input
				type="text"
				class="grow"
				v-model="inputValue"
				:placeholder="placeholder"
				:disabled="disabled"
				@focus="handleFocus"
				@blur="handleBlur"
			/>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 16 16"
				fill="currentColor"
				class="w-4 h-4 opacity-70"
			>
				<path
					fill-rule="evenodd"
					d="M9.965 11.026a5 5 0 1 1 1.06-1.06l2.755 2.754a.75.75 0 1 1-1.06 1.06l-2.755-2.754ZM10.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Z"
					clip-rule="evenodd"
				/>
			</svg>
		</label>
		<div
			v-if="isOpen"
			class="dropdown-content bg-base-200 top-14 max-h-96 overflow-auto flex-col rounded-md w-full"
			:style="{ width: dropdownWidth + 'px' }"
		>
			<ul class="menu menu-compact">
				<li
					v-for="(item, index) in displayOptions"
					:key="index"
					:tabindex="index + 1"
					@click="selectOption(item)"
					class="border-b border-b-base-content/10 w-full"
				>
					<button>{{ item.label }}</button>
				</li>
			</ul>
		</div>
	</div>
</template>

<script lang="ts">
import { ref, watch, computed, onMounted } from "vue";
import type { DropdownOption } from "../../data/candidate";

export default {
	name: "Autocomplete",
	props: {
		options: {
			type: Array<DropdownOption>,
			required: true,
		},
		value: {
			type: Object as () => DropdownOption | null,
			required: true,
		},
		placeholder: {
			type: String,
			required: true,
		},
		onChange: {
			type: Function,
			required: true,
		},
		disabled: {
			type: Boolean,
			default: false,
		},
	},
	setup(props) {
		const dropdownRef = ref<HTMLElement | null>(null);
		const inputValue = ref("");
		const isOpen = ref(false);
		const dropdownWidth = ref(0);

		const handleFocus = () => {
			isOpen.value = true;
			updateDropdownWidth();
		};

		const handleBlur = () => {
			setTimeout(() => {
				isOpen.value = false;
			}, 200);
		};

		const updateDropdownWidth = () => {
			if (!dropdownRef.value) return;
			dropdownWidth.value = dropdownRef.value.clientWidth || 0;
		};

		const displayOptions = computed(() => {
			if (!inputValue.value) {
				return props.options;
			}
			return props.options.filter((option) =>
				option.label.toLowerCase().includes(inputValue.value.toLowerCase()),
			);
		});

		const selectOption = (option: DropdownOption) => {
			inputValue.value = option.label;
			// this.$emit('change', option);
			props.onChange(option);
			handleBlur();
		};

		watch(
			() => props.value,
			(newValue) => {
				inputValue.value = newValue ? newValue.label : "";
			},
		);

		onMounted(() => {
			updateDropdownWidth();
		});

		return {
			dropdownRef,
			inputValue,
			isOpen,
			dropdownWidth,
			handleFocus,
			handleBlur,
			displayOptions,
			selectOption,
		};
	},
};
</script>

<style scoped>
/* Add any scoped styles if necessary */
</style>
